# Generated by Django 4.2.7 on 2023-12-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edc_crf", "0004_alter_crfstatus_device_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crfstatus",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "CRF Status",
                "verbose_name_plural": "CRF Status",
            },
        ),
        migrations.AddField(
            model_name="crfstatus",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="crfstatus",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddIndex(
            model_name="crfstatus",
            index=models.Index(
                fields=["-modified", "-created"], name="edc_crf_crf_modifie_6152c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crfstatus",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_crf_crf_user_mo_817af3_idx",
            ),
        ),
    ]
